"""
Export the best learned strategy for use inside the native MT5 Strategy Tester.

Phase 3 stores the top strategies per symbol/timeframe in
data_store/strategy_registry.json. The MT5 Expert Advisor
(experts/Mt5SmartBotEA.mq5) cannot read that nested JSON directly, so this
script flattens the chosen strategy into a simple, EA-friendly key=value file:

    experts/params/<SYMBOL>_<TIMEFRAME>.params

That file is loaded by the EA at runtime (from the terminal's MQL5\\Files folder;
see experts/README_EA.md for where to copy it). Only the indicators the EA
implements natively are exported; unknown indicators are skipped with a warning
so the EA and the Python side can evolve independently.

Usage
-----
    python scripts/export_strategy_for_ea.py
    python scripts/export_strategy_for_ea.py --symbol EURUSD --timeframe M15
    python scripts/export_strategy_for_ea.py --all

All text is standard ASCII English only.
"""

from __future__ import annotations

import argparse
import os
import sys


# Indicators the EA (Mt5SmartBotEA.mq5) understands natively. Keep this list in
# sync with the EA's ParseParams() switch.
EA_SUPPORTED_INDICATORS = ("ema", "sma", "rsi", "macd", "atr", "adx")


def _project_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _flatten_spec(spec: dict) -> list:
    """
    Turn a StrategySpec dict into flat key=value lines the EA can parse.

    Emitted keys:
        long_threshold, short_threshold, sl_atr_mult, tp_atr_mult
        ind.<name>.enabled, ind.<name>.weight, ind.<name>.<param>
    """
    lines = []
    lines.append("long_threshold=%s" % spec.get("long_threshold", 0.3))
    lines.append("short_threshold=%s" % spec.get("short_threshold", 0.3))
    lines.append("sl_atr_mult=%s" % spec.get("sl_atr_mult", 2.0))
    lines.append("tp_atr_mult=%s" % spec.get("tp_atr_mult", 3.0))

    indicators = spec.get("indicators", {}) or {}
    weights = spec.get("weights", {}) or {}
    skipped = []
    for name, params in indicators.items():
        if name not in EA_SUPPORTED_INDICATORS:
            skipped.append(name)
            continue
        lines.append("ind.%s.enabled=1" % name)
        lines.append("ind.%s.weight=%s" % (name, weights.get(name, 1.0)))
        if isinstance(params, dict):
            for pkey, pval in params.items():
                lines.append("ind.%s.%s=%s" % (name, pkey, pval))
    return lines, skipped


def _export_one(root, registry, symbol, timeframe, out_dir):
    key = "%s|%s" % (symbol, timeframe)
    section = registry.get(key, {})
    top = section.get("top", [])
    if not top:
        print("  [WARN] No learned strategy in registry for %s %s. "
              "Run 'python main.py --mode search' first." % (symbol, timeframe))
        return False
    spec = top[0].get("spec", {})
    lines, skipped = _flatten_spec(spec)
    if skipped:
        print("  [note] Skipped indicators not supported by the EA for %s %s: %s"
              % (symbol, timeframe, ", ".join(sorted(set(skipped)))))
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "%s_%s.params" % (symbol, timeframe))
    header = [
        "# Auto-generated by scripts/export_strategy_for_ea.py",
        "# Strategy params for the MT5 Strategy Tester EA (Mt5SmartBotEA.mq5).",
        "# Copy this file into your terminal's MQL5\\Files folder.",
        "symbol=%s" % symbol,
        "timeframe=%s" % timeframe,
    ]
    with open(out_path, "w", encoding="ascii") as fh:
        fh.write("\n".join(header + lines) + "\n")
    print("  [ OK ] %s %s -> %s" % (symbol, timeframe, out_path))
    return True


def main(argv=None) -> int:
    root = _project_root()
    if root not in sys.path:
        sys.path.insert(0, root)

    from config.loader import load_config
    from core.utils.helpers import read_json

    parser = argparse.ArgumentParser(
        description="Export the best learned strategy for the MT5 tester EA."
    )
    parser.add_argument("--config", default=None)
    parser.add_argument("--symbol", default=None,
                        help="Single symbol (default: all config symbols).")
    parser.add_argument("--timeframe", default=None,
                        help="Timeframe label (default: config mt5.timeframe).")
    parser.add_argument("--all", action="store_true",
                        help="Export every configured symbol.")
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    cfg = load_config(args.config)
    registry_rel = cfg.get_path("memory.registry_file",
                                "data_store/strategy_registry.json")
    registry_path = registry_rel if os.path.isabs(registry_rel) \
        else os.path.join(root, registry_rel)
    registry = read_json(registry_path, default={}) or {}
    if not registry:
        print("[ERROR] Registry is empty (%s). Run a search first:" % registry_path)
        print("        python main.py --mode search")
        return 1

    timeframe = args.timeframe or str(cfg.get_path("mt5.timeframe", "M15"))
    if args.symbol:
        symbols = [args.symbol.upper()]
    else:
        symbols = [str(s) for s in cfg.get_path("mt5.symbols", ["EURUSD"])]

    out_dir = os.path.join(root, "experts", "params")
    print("Exporting EA strategy params to %s" % out_dir)
    exported = 0
    for sym in symbols:
        if _export_one(root, registry, sym, timeframe, out_dir):
            exported += 1

    print("Done. Exported %d file(s)." % exported)
    print("Next: copy experts/params/*.params into your terminal's MQL5\\Files "
          "folder, then run Mt5SmartBotEA in the Strategy Tester.")
    return 0 if exported > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
