"""
Chaos-monkey harness (UPGRADE_PLAN Phase U6.6).

A deliberately hostile TEST mode. It takes a clean price history and injects
broker "nastiness" into a COPY of it, then re-scores each registry strategy on
the clean series vs the chaos series and reports which strategies DEGRADE
GRACEFULLY and which SHATTER. Nothing here ever trades, promotes, or edits the
registry - it is a purely offline stress diagnostic that answers one question:

    "If the broker misbehaves for a week, does my edge survive or evaporate?"

Injected nastiness (each independently config-gated, all default OFF so the
whole feature is a no-op until asked for):

  - spread storms   : globally widen the cost model by a multiplier (the
                      backtester already reads spread from config, so this is a
                      config override, not a data edit).
  - requotes        : jitter a fraction of bar OPENS by +/- a few points so
                      next-open fills land at a slightly worse-than-expected
                      price (models a broker requoting the entry).
  - missed bars     : drop a fraction of bars entirely (models a data feed gap
                      / a bar the EA never saw), which also stretches the
                      remaining bars into small gaps.
  - partial fills   : shrink the effective position size on a fraction of trades
                      by scaling the fixed lot down (models the broker filling
                      only part of the requested volume).

The harness is intentionally REPRODUCIBLE: every random choice is driven by a
seed so a chaos verdict can be regenerated byte-for-byte.

Classification
--------------
For each strategy we compute a degradation ratio on net_profit (and require the
chaos run to still be non-catastrophic). A strategy is:

  - GRACEFUL : chaos net_profit stays above `graceful_floor_mult` of its clean
               net_profit (e.g. keeps >= 40% of its edge) AND is still positive.
  - FRAGILE  : keeps some edge but drops below the graceful floor (a warning).
  - SHATTERED: goes non-positive (or catastrophically negative) under chaos.

Pure standard library, ASCII English only, Windows 7 + Python 3.8 friendly.
"""

from __future__ import annotations

import copy
import random
import time
from typing import Any, Dict, List, Optional

from core.data.data_feed import OHLCV
from core.strategy.strategy import Strategy, StrategySpec
from core.strategy.backtester import Backtester
from core.utils.logger import get_logger


# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #
class ChaosConfig(object):
    """Parsed, defensively-read view of the ``general.chaos_monkey`` block."""

    def __init__(self, cfg: Any):
        block = {}
        try:
            block = cfg.get_path("general.chaos_monkey", {}) or {}
        except Exception:
            block = {}
        if not hasattr(block, "get"):
            block = {}

        self.enabled = bool(block.get("enabled", False))
        self.seed = self._int(block, "seed", 20240607)
        # Individual nastiness switches (all default off).
        self.spread_storm = bool(block.get("spread_storm", False))
        self.requotes = bool(block.get("requotes", False))
        self.missed_bars = bool(block.get("missed_bars", False))
        self.partial_fills = bool(block.get("partial_fills", False))
        # Intensities.
        self.spread_mult = self._float(block, "spread_mult", 2.0)
        self.requote_frac = self._clamp01(self._float(block, "requote_frac", 0.15))
        self.requote_points = self._float(block, "requote_points", 8.0)
        self.missed_frac = self._clamp01(self._float(block, "missed_frac", 0.05))
        self.partial_frac = self._clamp01(self._float(block, "partial_frac", 0.20))
        self.partial_min_scale = self._clamp01(
            self._float(block, "partial_min_scale", 0.5))
        # Classification thresholds.
        self.graceful_floor_mult = self._float(block, "graceful_floor_mult", 0.4)
        # Chaos net must not fall below this fraction of starting balance to be
        # anything other than SHATTERED (catastrophe guard).
        self.catastrophe_mult = self._float(block, "catastrophe_mult", -0.25)

    @staticmethod
    def _float(block, key, default):
        try:
            return float(block.get(key, default))
        except (TypeError, ValueError):
            return float(default)

    @staticmethod
    def _int(block, key, default):
        try:
            return int(block.get(key, default))
        except (TypeError, ValueError):
            return int(default)

    @staticmethod
    def _clamp01(x):
        try:
            x = float(x)
        except (TypeError, ValueError):
            return 0.0
        if x < 0.0:
            return 0.0
        if x > 1.0:
            return 1.0
        return x

    def any_data_nastiness(self):
        """True if any nastiness that mutates the price series is on."""
        return bool(self.requotes or self.missed_bars)

    def any_nastiness(self):
        return bool(self.spread_storm or self.requotes or self.missed_bars
                    or self.partial_fills)
