"""
Chaos-monkey harness (UPGRADE_PLAN Phase U6.6).

A deliberately hostile TEST mode. It takes a clean price history and injects
broker "nastiness" into a COPY of it, then re-scores each registry strategy on
the clean series vs the chaos series and reports which strategies DEGRADE
GRACEFULLY and which SHATTER. Nothing here ever trades, promotes, or edits the
registry - it is a purely offline stress diagnostic that answers one question:

    "If the broker misbehaves for a week, does my edge survive or evaporate?"

Injected nastiness (each independently config-gated, all default OFF so the
whole feature is a no-op until asked for):

  - spread storms   : globally widen the cost model by a multiplier (the
                      backtester already reads spread from config, so this is a
                      config override, not a data edit).
  - requotes        : jitter a fraction of bar OPENS by +/- a few points so
                      next-open fills land at a slightly worse-than-expected
                      price (models a broker requoting the entry).
  - missed bars     : drop a fraction of bars entirely (models a data feed gap
                      / a bar the EA never saw), which also stretches the
                      remaining bars into small gaps.
  - partial fills   : shrink the effective position size on a fraction of trades
                      by scaling the fixed lot down (models the broker filling
                      only part of the requested volume).

The harness is intentionally REPRODUCIBLE: every random choice is driven by a
seed so a chaos verdict can be regenerated byte-for-byte.

Classification
--------------
For each strategy we compute a degradation ratio on net_profit (and require the
chaos run to still be non-catastrophic). A strategy is:

  - GRACEFUL : chaos net_profit stays above `graceful_floor_mult` of its clean
               net_profit (e.g. keeps >= 40% of its edge) AND is still positive.
  - FRAGILE  : keeps some edge but drops below the graceful floor (a warning).
  - SHATTERED: goes non-positive (or catastrophically negative) under chaos.

Pure standard library, ASCII English only, Windows 7 + Python 3.8 friendly.
"""

from __future__ import annotations

import copy
import random
import time
from typing import Any, Dict, List, Optional

from core.data.data_feed import OHLCV
from core.strategy.strategy import Strategy, StrategySpec
from core.strategy.backtester import Backtester
from core.utils.logger import get_logger


# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #
class ChaosConfig(object):
    """Parsed, defensively-read view of the ``general.chaos_monkey`` block."""

    def __init__(self, cfg: Any):
        block = {}
        try:
            block = cfg.get_path("general.chaos_monkey", {}) or {}
        except Exception:
            block = {}
        if not hasattr(block, "get"):
            block = {}

        self.enabled = bool(block.get("enabled", False))
        self.seed = self._int(block, "seed", 20240607)
        # Individual nastiness switches (all default off).
        self.spread_storm = bool(block.get("spread_storm", False))
        self.requotes = bool(block.get("requotes", False))
        self.missed_bars = bool(block.get("missed_bars", False))
        self.partial_fills = bool(block.get("partial_fills", False))
        # Intensities.
        self.spread_mult = self._float(block, "spread_mult", 2.0)
        self.requote_frac = self._clamp01(self._float(block, "requote_frac", 0.15))
        self.requote_points = self._float(block, "requote_points", 8.0)
        self.missed_frac = self._clamp01(self._float(block, "missed_frac", 0.05))
        self.partial_frac = self._clamp01(self._float(block, "partial_frac", 0.20))
        self.partial_min_scale = self._clamp01(
            self._float(block, "partial_min_scale", 0.5))
        # Classification thresholds.
        self.graceful_floor_mult = self._float(block, "graceful_floor_mult", 0.4)
        # Chaos net must not fall below this fraction of starting balance to be
        # anything other than SHATTERED (catastrophe guard).
        self.catastrophe_mult = self._float(block, "catastrophe_mult", -0.25)

    @staticmethod
    def _float(block, key, default):
        try:
            return float(block.get(key, default))
        except (TypeError, ValueError):
            return float(default)

    @staticmethod
    def _int(block, key, default):
        try:
            return int(block.get(key, default))
        except (TypeError, ValueError):
            return int(default)

    @staticmethod
    def _clamp01(x):
        try:
            x = float(x)
        except (TypeError, ValueError):
            return 0.0
        if x < 0.0:
            return 0.0
        if x > 1.0:
            return 1.0
        return x

    def any_data_nastiness(self):
        """True if any nastiness that mutates the price series is on."""
        return bool(self.requotes or self.missed_bars)

    def any_nastiness(self):
        return bool(self.spread_storm or self.requotes or self.missed_bars
                    or self.partial_fills)


# --------------------------------------------------------------------------- #
# Data-series injectors (requotes, missed bars)
# --------------------------------------------------------------------------- #
def _infer_point(ohlcv):
    """Cheap point-size guess so requote jitter is in sensible price units."""
    from core.utils.helpers import symbol_offline_specs
    try:
        return float(symbol_offline_specs(getattr(ohlcv, "symbol", ""))["point"])
    except Exception:
        return 0.0001


def inject_requotes(ohlcv, frac, points, rng):
    """Return a COPY of ohlcv with a `frac` of bar OPENS jittered by +/- up to
    `points` points. Only the OPEN is perturbed because next-open fills are what
    a requote hits; high/low/close stay intact so indicator signals are
    unchanged and we isolate the fill-price damage. A no-op when frac<=0."""
    out = ohlcv.slice(0, len(ohlcv))
    if frac <= 0.0 or points <= 0.0 or len(out) == 0:
        return out
    point = _infer_point(ohlcv)
    jitter_max = points * point
    opens = list(out.open)
    highs = out.high
    lows = out.low
    n = len(opens)
    for i in range(n):
        if rng.random() >= frac:
            continue
        # Signed jitter; a requote can be better or worse, but we bias WORSE by
        # drawing the magnitude uniformly and letting sign be random - the
        # pessimistic sim already halves-spread against us on top of this.
        delta = rng.uniform(-jitter_max, jitter_max)
        new_open = opens[i] + delta
        # Keep the open inside the bar's own [low, high] so the bar stays valid.
        hi = highs[i] if i < len(highs) else new_open
        lo = lows[i] if i < len(lows) else new_open
        if new_open > hi:
            new_open = hi
        if new_open < lo:
            new_open = lo
        opens[i] = new_open
    out.open = opens
    return out


def inject_missed_bars(ohlcv, frac, rng):
    """Return a COPY of ohlcv with a `frac` of NON-EDGE bars dropped, modelling a
    data-feed gap / a bar the EA never received. The first and last bars are
    always kept so slicing / warmup logic elsewhere stays well-defined. A no-op
    when frac<=0."""
    n = len(ohlcv)
    out = ohlcv.slice(0, n)
    if frac <= 0.0 or n < 5:
        return out
    keep_idx = []
    for i in range(n):
        if i == 0 or i == n - 1:
            keep_idx.append(i)
            continue
        if rng.random() < frac:
            continue  # drop this bar
        keep_idx.append(i)
    if len(keep_idx) == n:
        return out
    res = OHLCV(out.symbol, out.timeframe)
    res.time = [out.time[i] for i in keep_idx] if out.time else []
    res.open = [out.open[i] for i in keep_idx]
    res.high = [out.high[i] for i in keep_idx]
    res.low = [out.low[i] for i in keep_idx]
    res.close = [out.close[i] for i in keep_idx]
    res.volume = [out.volume[i] for i in keep_idx] if out.volume else []
    return res


def build_chaos_series(ohlcv, ccfg, rng):
    """Apply every enabled DATA-mutating injector, in a fixed order, to a copy
    of ohlcv. Cost/lot nastiness is applied via config, not here."""
    series = ohlcv.slice(0, len(ohlcv))
    if ccfg.missed_bars:
        series = inject_missed_bars(series, ccfg.missed_frac, rng)
    if ccfg.requotes:
        series = inject_requotes(series, ccfg.requote_frac,
                                 ccfg.requote_points, rng)
    return series


def chaos_config_override(cfg, ccfg):
    """Return a deep-copied config with the COST/LOT nastiness applied:
      - spread storm  : multiply spread_points (and spread_model.base_points).
      - partial fills : scale fixed_lot down toward partial_min_scale (a blunt
                        proxy for "you rarely get your full requested size").
    The data injectors are handled separately (they mutate the series)."""
    clone = copy.deepcopy(cfg)
    try:
        bt = clone.get_path("backtest", {})
        if hasattr(bt, "get"):
            if ccfg.spread_storm:
                base = float(bt.get("spread_points", 10) or 10)
                bt["spread_points"] = base * ccfg.spread_mult
                sm = bt.get("spread_model", None)
                if hasattr(sm, "get") and len(sm) > 0:
                    sm_base = float(sm.get("base_points", base) or base)
                    sm["base_points"] = sm_base * ccfg.spread_mult
            if ccfg.partial_fills:
                lot = float(bt.get("fixed_lot", 0.1) or 0.1)
                # Expected size multiplier if `partial_frac` of fills are cut to
                # `partial_min_scale`: E = (1-f) + f*min_scale.
                f = ccfg.partial_frac
                eff = (1.0 - f) + f * ccfg.partial_min_scale
                bt["fixed_lot"] = lot * eff
    except Exception:
        pass
    return clone
